spring.application.name=turma-sala-b-many-to-many

# Altere estes tres valores ou informe as variaveis de ambiente.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/uniamerica}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration


spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
